export const lightThemeVars = {
  headerBackgroundColor: '#393231',
  headerTextColor: 'snow',
  headerTextHoverColor: 'gray',
  mainBackgroundColor: '#D9D9D9   ',
  mainTextColor: 'black',
  lightModeBackground: 'snow',
  cardBackgroundColor: 'snow',
  loadMoreBtnColor: '#393231',
  loadMoreBtnTextColor: '#ffffff',
  loadMoreHoverColor: 'black',
  loadMoreDisabledColor: '#c2c2c2',
  popupBackgroundColor: '#393231',
  detailsIconFillColor: 'black',
  detailsIconSubContainer: '#f5f5f5',
  ratingIconFillColor: 'black',
  removeAddButtons: '#442727',
  removeAddText: 'white',
  sliderArrow: '#442727',
  aboutTextColor: 'black',
  aboutTwiceBlock: '#393231',
  achievementsCardColor: 'white',
};

export const darkThemeVars = {
  headerBackgroundColor: '#2C3639',
  headerTextColor: '#DCD7C9',
  headerTextHoverColor: 'gray',
  mainBackgroundColor: '#3F4E4F',
  mainTextColor: '#DCD7C9',
  lightModeBackground: 'gold',
  cardBackgroundColor: '#2C3639',
  loadMoreBtnColor: '#2C3639',
  loadMoreBtnTextColor: 'snow',
  loadMoreHoverColor: '#1c292d',
  loadMoreDisabledColor: 'gray',
  popupBackgroundColor: '#2C3639',
  detailsIconFillColor: 'black',
  detailsIconSubContainer: 'rgb(44, 54, 57)',
  ratingIconFillColor: 'white',
  removeAddButtons: 'white',
  removeAddText: 'black',
  sliderArrow: 'white',
  aboutTextColor: '#DCD7C9',
  aboutTwiceBlock: '#2C3639',
  achievementsCardColor: '#2C3639',
};
