export const lightThemeVars = {
  headerBackgroundColor: '#7f7e7a',
  headerTextColor: 'snow',
  headerTextHoverColor: 'gray',
  mainBackgroundColor: 'snow',
  mainTextColor: 'black',
  lightModeBackground: 'snow',
  cardBackgroundColor: 'snow',
  loadMoreBtnColor: '#7f7e7a',
  loadMoreBtnTextColor: '#ffffff',
  loadMoreDisabledColor: '#c2c2c2',
  popupBackgroundColor: '#7f7e7a',
  detailsIconFillColor: 'black',
  ratingIconFillColor: 'black',
  removeAddButtons: '#442727',
  removeAddText: 'white',
  sliderArrow: '#442727',
};

export const darkThemeVars = {
  headerBackgroundColor: '#2C3639',
  headerTextColor: '#DCD7C9',
  headerTextHoverColor: 'gray',
  mainBackgroundColor: '#3F4E4F',
  mainTextColor: '#DCD7C9',
  lightModeBackground: 'gold',
  cardBackgroundColor: '#2C3639',
  loadMoreBtnColor: '#2C3639',
  loadMoreBtnTextColor: 'snow',
  loadMoreDisabledColor: 'gray',
  popupBackgroundColor: '#2C3639',
  detailsIconFillColor: 'black',
  ratingIconFillColor: 'white',
  removeAddButtons: 'white',
  removeAddText: 'black',
  sliderArrow: 'white',
};
